trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: CacheBeta@0
  inputs:
    key: |
      $(Agent.OS)
      $(Build.SourcesDirectory)/package-lock.json
    path: '$(Build.SourcesDirectory)/node_modules'
  displayName: 'Cache node_modules'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm test
  displayName: 'Install node modules & Test'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm run build'
  displayName: 'Build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: npm run dist
  env:
    GH_TOKEN: $(GH_TOKEN)
  displayName: 'Create and upload distributables'
