trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

# Temporary disabled caching due to issues on Mac and Linux (executable permissions?)
#- task: CacheBeta@0
#  inputs:
#    key: |
#      $(Agent.OS)
#      $(Build.SourcesDirectory)/package-lock.json
#    path: '$(Build.SourcesDirectory)/node_modules'
#  displayName: 'Cache node_modules'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm install'
  displayName: 'Install node modules'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm test'
  displayName: 'Test'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm run build'
  displayName: 'Build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: npm run dist
  env:
    GH_TOKEN: $(GH_TOKEN)
  displayName: 'Create and upload distributables'
